### ISSUE TITLE
U.S. levels 2 and 3 not updating

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#164]
No updates since 4/24. Thank you for all that you do.

**Comment by eguidotti** [comment]
Yes thanks, it should have been solved already but it takes some time to generate the data files.
The data should be updated in a couple of hours max. Thanks for your patience.

**Comment by kenshermock** [comment]
Thank you, Emanuele. Level 3 updated, but level 2 has not refreshed as of this email.  Best, Ken

From: Emanuele Guidotti ***@***.***>
Reply-To: covid19datahub/COVID19 ***@***.***>
Date: Friday, March 26, 2021 at 8:22 PM
To: covid19datahub/COVID19 ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [covid19datahub/COVID19] U.S. levels 2 and 3 not updating (#164)


      External Email - Use Caution





Yes thanks, it should have been solved already but it takes some time to generate the data files.
The data should be updated in a couple of hours max. Thanks for your patience.

**Comment by eguidotti** [comment]
Hello @kenshermock, I can see all the `raw` data up-to-date. Please make sure to switch to the `raw` data by 1 April as recommended here https://covid19datahub.io/news/index.html and in the README:

> Due to the incresing size of the data files, we will stop to provide the pre-processed data on 01 April 2021, so to improve the update and storage of the raw data. Please switch to the raw data if you are still using the pre-processed files.

Please let me know if this works for you. Thanks!

**Comment by kenshermock** [comment]
Thank you. Level 2 still not updated since 3/24.  Are you able to share the processing code you apply to your data? I imagine re-producing it from scratch would be quite challenging.

From: Emanuele Guidotti ***@***.***>
Reply-To: covid19datahub/COVID19 ***@***.***>
Date: Saturday, March 27, 2021 at 5:11 PM
To: covid19datahub/COVID19 ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: Re: [covid19datahub/COVID19] U.S. levels 2 and 3 not updating (#164)


      External Email - Use Caution





Hello @kenshermock<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkenshermock&data=04%7C01%7Cken%40jhmi.edu%7Cfb2e7469d3f54bdd119b08d8f164e2f3%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637524762892683232%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p2upUMfxoQKhA8pGA9mxljykdvanFrJgpaeCyF2p4uQ%3D&reserved=0>, I can see all the raw data up-to-date. Please make sure to switch to the raw data by 1 April as recommended here https://covid19datahub.io/news/index.html<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcovid19datahub.io%2Fnews%2Findex.html&data=04%7C01%7Cken%40jhmi.edu%7Cfb2e7469d3f54bdd119b08d8f164e2f3%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637524762892693190%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tb9m9MNdDTw%2B3%2B8CKarXv%2F1zg7cEIvHBS%2FjsBoRwzsc%3D&reserved=0> and in the README:

Due to the incresing size of the data files, we will stop to provide the pre-processed data on 01 April 2021, so to improve the update and storage of the raw data. Please switch to the raw data if you are still using the pre-processed files.

Please let me know if this works for you. Thanks!

**Comment by eguidotti** [comment]
Hi @kenshermock, it is weird. I get the data up-to-date as of 2021-03-27 with the following code. Maybe some caching issues?
```R
x <- covid19("USA", level = 2)
max(x$date)
# [1] "2021-03-27"
```

Regarding the pre-processing, that's minimal. You can find the description [here](https://covid19datahub.io/articles/data.html) and the code [here](https://github.com/covid19datahub/COVID19/blob/d6fd102dfc83c1a7a97e628968daa18bc5cb9704/R/covid19.R) at lines 275-301. The variables affected are defined [here](https://github.com/covid19datahub/COVID19/blob/d4416dd4af0274f053f4b7fad991bda583af81c8/R/utils.R) at lines 73-99.

Hope this helps!

**Comment by kenshermock** [comment]
Thank you. The level 3 raw file is updated only to 3/25/2021.

From: Emanuele Guidotti ***@***.***>
Reply-To: covid19datahub/COVID19 ***@***.***>
Date: Sunday, March 28, 2021 at 12:57 PM
To: covid19datahub/COVID19 ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: Re: [covid19datahub/COVID19] U.S. levels 2 and 3 not updating (#164)


      External Email - Use Caution





Hi @kenshermock<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkenshermock&data=04%7C01%7Cken%40jhmi.edu%7C9a2a51cd2f6a4dec485a08d8f20a818b%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637525474227003640%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PvT38RodxcD5SsgrGvWOfg8DQtn53XIctBjvhO1MXn8%3D&reserved=0>, it is weird. I get the data up-to-date as of 2021-03-27 with the following code. Maybe some caching issues?

x <- covid19("USA", level = 2)

max(x$date)

# [1] "2021-03-27"

Regarding the pre-processing, that's minimal. You can find the description here<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcovid19datahub.io%2Farticles%2Fdata.html&data=04%7C01%7Cken%40jhmi.edu%7C9a2a51cd2f6a4dec485a08d8f20a818b%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637525474227003640%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3LseoPseEMQX4zjJp3uluZK19%2Fz1S666wdqwcGvZOLk%3D&reserved=0> and the code here<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcovid19datahub%2FCOVID19%2Fblob%2Fd6fd102dfc83c1a7a97e628968daa18bc5cb9704%2FR%2Fcovid19.R&data=04%7C01%7Cken%40jhmi.edu%7C9a2a51cd2f6a4dec485a08d8f20a818b%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637525474227013596%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ON5g%2Fjz95WikrJa9WhIOFFDIKTo88UCB0VZoxeuQqRA%3D&reserved=0> at lines 275-301. The variables affected are defined here<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcovid19datahub%2FCOVID19%2Fblob%2Fd4416dd4af0274f053f4b7fad991bda583af81c8%2FR%2Futils.R&data=04%7C01%7Cken%40jhmi.edu%7C9a2a51cd2f6a4dec485a08d8f20a818b%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637525474227013596%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DYeJB4SYu6QlRODVxHHxwtfMAk1HpTXDP548wJVCKag%3D&reserved=0> at lines 73-99.

Hope this helps!

**Comment by eguidotti** [comment]
Mmm... I get up-to-date `raw` data also for level 3:
```R
x <- covid19("USA", level = 3)
max(x$date)
# [1] "2021-03-27"
```
The only file that is not updated is the pre-processed data for level 3 (that in any case will not be supported starting from 1 April).
